version: "3.9"

services:
  db:
    image: postgres:15
    container_name: meeting_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build: ./Frontend
    container_name: frontend_service
    ports:
      - "3000:80"         # Browser â†’ localhost:3000
    depends_on:
      - user_service
      - room_service
      - booking_service
    restart: always


  user_service:
    build: ./Backend/user_service
    container_name: user_service
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8001:8000"

  room_service:
    build: ./Backend/room_service
    container_name: room_service
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8002:8000"

  booking_service:
    build: ./Backend/booking_service
    container_name: booking_service
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8003:8000"

volumes:
  postgres_data:
